version: "3.7"

services:
    bot:
        build: ./docker/
        command: poetry run python main.py
        restart: always
        volumes:
            - ./config_override.json:/app/config_override.json
            - ./lastId.json:/app/lastId.json
